# -*- coding: utf-8 -*-
"""data_creation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IL9xZ5TwlAykpXUlsXKCFtBG-40Sxbm3
"""


from faker import Faker

fake = Faker()

import random

def temperature(date):
    if(date.month<=2 or date.month>=12):
        return random.randint(-30,10)
    elif(date.month>=3 and date.month<6):
        return random.randint(-10,25)
    elif(date.month>=6 and date.month<9):
        return random.randint(0,40)
    elif(date.month>=9 and date.month<12):
        return random.randint(-20,10)

def humidity():
    return random.randint(20, 80)

def pressure():
    return random.randint(620, 800)

def clouds(precipitation):
    if(precipitation):
        return random.randint(70,100)
    else:
        return random.randint(0,100)

import pandas as pd

df_train = pd.DataFrame(
    [
        {

            "date": fake.date_this_century(),
            "time": fake.time(),
            "humidity": humidity(),
            "pressure": pressure(),
            "clouds": 0,
            "precipitation": fake.boolean(),
            "temperature": 0,
        }
        for _ in range(1000)
    ]
)

df_train['temperature'] = df_train['date'].apply(lambda x: temperature(x))
df_train['clouds'] = df_train['precipitation'].apply(lambda x: clouds(x))

import os
if not os.path.isdir("train"):
     os.mkdir("train")

df_train.to_csv (r'train/train.csv', index= False )

df_test = pd.DataFrame(
    [
        {

            "date": fake.date_this_century(),
            "time": fake.time(),
            "humidity": humidity(),
            "pressure": pressure(),
            "clouds": 0,
            "precipitation": fake.boolean(),
            "temperature": 0,
        }
        for _ in range(300)
    ]
)

df_test['temperature'] = df_test['date'].apply(lambda x: temperature(x))
df_test['clouds'] = df_test['precipitation'].apply(lambda x: clouds(x))

if not os.path.isdir("test"):
     os.mkdir("test")

df_test.to_csv (r'test/test.csv', index= False )