# -*- coding: utf-8 -*-
"""model_testing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15PeAC2bS8t6fENfKX19CEmOKkGItimfO
"""

import pandas as pd

df=pd.read_csv("test/test_preprocessing.csv")

X=df.drop("precipitation", axis=1)
y=df.precipitation

import pickle

filename = 'finalized_model.sav'

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X, y)
print(result)